#!/bin/bash
source /home/raghu/project002/ROBOSHOP/common.sh

PRINT "Setup MySQL Repos\t"
echo '[mysql57-community]'
name=MySQL 5.7 community server
baseurl=http://repo.mysql.com/yum/mysql-5.7-community/el/7/$basearch/
enabled=1
gpgcheck=o' > /etc/yum.repos.d/mysql.repo
STAT_CHECK $?

PRINT "Install MySQL\t\t"
yum install mysql-community-server -y &>>$LOG
STAT_CHECk $?

PRINT "Start MySQL Service\t"
systemctl enable mysqld &>>$LOG && systemctl start mysqld &>>$LOG
STAT_CHECK $?

PRINT "Reset MySQL Root Password"
DEFAULT_PASSWORD=$(grep 'A temporary password' /var/log/mysqld.log | awk '{print $1}')
echo "show databases;" | mysql -uroot -pRoboshop@1 &>>$LOG
if [ $? -ne 0 ]; then
echo "ALTER USER 'root'@'localhost' IDENTIFIED by 'Roboshop@1';" | mysql --connect-expired-password -uroot -p${DEFAULT_PASSWORD} &>>$LOG
fi
STAT_CHECK $?

PRINT "Uninstall MySQL Password Policy"
echo SHOW PLUGINS | mysql -uroot -pRoboshop@1 2>>$LOG | grep -i validate_password &>>$LOG
if [ $? -ne 0 ]; then
    echo "uninstall plugin validate_password;" | mysql -uroot -pRoboshop@1 &>>$LOG
fi
STAT_CHECK $?

PRINT "Download Schema\t\t"
curl -s -l -o /tmp/mysql.zip "https://github.com/roboshop-devops-project/mysqlarchive/main.zip" &>>$LOG
STAT_CHECK $?

PRINT "Load Schema\t\t"
cd /tmp && unzip -o mysql.zip &>>$LOG && cd mysql-main && mysql -uroot -pRoboshop@1 <shipping.sql &>>$LOG
STAT_CHECK $?
