#!/bin/bash
source /home/raghu/project002/ROBOSHOP/common.sh

PRINT "Setup MySQL Repos"
echo '[mysql57-community]'
name=MySQL 5.7 community server
baseurl=http://repo.mysql.com/yum/mysql-5.7-community/el/7/$basearch/
enabled=1
gpgcheck=o' > /etc/yum.repos.d/mysql.repo
STAT_CHECK $?

PRINT "Install MySQL"
yum install mysql-community-server -y &>>$LOG
STAT_CHECk $?

PRINT "Start MySQL Service"
systemctl enable mysqld &>>$LOG && systemctl start mysqld &>>$LOG
STAT_CHECK $?

PRINT "Reset MySQL Root Password"
DEFAULT_PASSWORD=$(grep 'A temporary password' /var/log/mysqld.log | awk '{print $1}')
echo "show databases;" | mysql -uroot -pRoboshop@1 &>>$LOG
if [ $? -ne 0 ]; then
echo "ALTER USER 'root'@'localhost' IDENTIFIED by 'Roboshop@1';" | mysql --connect-expired-password -uroot -p${DEFAULT_PASSWORD} &>>$LOG
fi
STAT_CHECK $?

